### ISSUE TITLE
Only credit card

### ISSUE THREAD

**Issue by wsandoval93** [mercadopago/px-hybrid#10]
I'm using the plugin and it works fine, but i only need to accept "Credit Cards". And process the payments only for "Venezuela" it's possible to do this? How can i customize, i don't know how to use the other methods, the documentation is too short! Please i need more information about this...

**Comment by mreverter** [comment]
Hi! You have to create an account in [Mercado Pago Venezuela](https://www.mercadopago.com.ve), and use your credentials (get them [here](https://www.mercadopago.com.ve)).

You can use the services layer from our SDK, here's the documentation:
[Mercado Pago docs](http://mercadopago.github.io/px-hybrid/f1.html)

Also, you could try our [Cards UI Component](http://mercadopago.github.io/px-hybrid/f2.html#f2_payment_vault). 

However, the latter is not fully adapted to Venezuela yet (I've tried it and got a few error screens when the user inputs an invalid identification number).

**Comment by wsandoval93** [comment]
Thanks for the info, but i'm getting an error now, when i'm trying to upload my ipa to the AppStore.

![captura de pantalla 2016-11-03 a las 5 06 16 p m](https://cloud.githubusercontent.com/assets/22642569/19985135/a196fe02-a1e7-11e6-9c83-20fdec5313ca.png)

If i remove the MercadoPago Framework it works! But i need to use the Framework in Production now, what can i do??

Thanks!
