### ISSUE TITLE
Archive error iOS

### ISSUE THREAD

**Issue by wsandoval93** [mercadopago/px-hybrid#11]
When im trying to upload the app to the AppStore im getting this errors:

![captura de pantalla 2016-11-04 a las 12 49 52 p m](https://cloud.githubusercontent.com/assets/22642569/20014358/13a37e94-a28d-11e6-933c-30a8057fc98a.png)

I have checked my Copy Bundle Resources, but everything is fine!

![captura de pantalla 2016-11-04 a las 12 51 23 p m](https://cloud.githubusercontent.com/assets/22642569/20014387/2e46e39e-a28d-11e6-965c-c0531445da89.png)

Please i need to upload this app.

Thanks!

**Comment by edentorres** [comment]
Solved in 1.1.7
