### ISSUE TITLE
Error en Android

### ISSUE THREAD

**Issue by wsandoval93** [mercadopago/px-hybrid#12]
Tengo un error al iniciar la función "startCheckout()" en Android, si utilizo el "prefId" que uds dan en el ejemplo si inicia, pero cuando utilizo un "prefId" creado por el API de MercadoPago en PHP me da el siguiente error:

![screenshot_2016-11-04-19-31-14](https://cloud.githubusercontent.com/assets/22642569/20025894/ca05ccdc-a2c9-11e6-9d76-e52398dca122.png)

En iOS si me funciona con el "prefId" que devuelve el API, por ejemplo este:

> "175571043-13faed3e-ad6c-4d0e-a8da-67c9a2bc9687"

Igualmente si intento colocar ese "prefId" ya al llamar la función, tampoco me funciona.

Para crear el pref id, lo hago de la siguiente manera:

`
//Datos para crear la preferencia de compra de MercadoPago
			$preference_data = [
				"items" => $items_array,
				"payer" => [
					"name" => $first_name,
					"surname" => $last_name,
					"email" => $email,
					"phone" => [
						"area_code" => "+58",
						"number" => $phone
					],
					"address" => [
						"street_name" => $address_1,
						"street_number" => 0,
						"zip_code" => $postcode
					]
				]
			];

			//Crear Id de preferencia de pago
			$preference = $mp->create_preference($preference_data);
			$preference_id = json_encode($preference["response"]["id"]);`

Estoy llamando al método, de la siguiente forma:

`
        var prefId = $rootScope.actualPrefId.toString();
	var orderId = $rootScope.actualOrderId;

	//Codigo para mercadopago
	var publicKey = "TEST-e3438267-8dac-4ed6-9511-43822524205e";
	var colorMP = "#8dd7f7";
	
	$scope.startCheckout = function() {
		// Iniciar el checkout de MercadoPago
		MercadoPago.startCheckout(publicKey, prefId, colorMP, false, successTwo, failureTwo);
	}

	// Espera los resultados del checkout
	var successTwo = function(payment) {
		if (payment !== null){
			// Manejo de exito
		} else {
			// No concretó
		}
	};
	var failureTwo = function(error) {
		// Manejo de error
	};`

La función $scope.startCheckout, es llamada desde un botón en la vista.

**Comment by wsandoval93** [comment]
Ya resolví el problema, cambié el publickKey de prueba por el de producción y me funcionó.

**Comment by DNAngeluS** [comment]
Hola @edentorres, tengo este mismo problema, la repuesta que obtengo de la Actividad cuando quiero hacer el checkout con una preferencia creada con la API es "Inactive preference". Sin embargo si uso esa preferencia y accedo por la aplicación web puedo realizar el pago sin problema. Hice pruebas tanto como el publicKey de TEST y  de PROD.

La preferencia la estamos creando con al SDK de Node.js de la siguiente manera.
```


var preference = {
  items: [{
    title: "Testing payments",
    quantity: 1,
    currency_id: "ARS",
    unit_price: price
  }],
  payer: {
    email: reservation.User.email
  },
  expires: true,
  expiration_date_from: date.toISOString().replace('Z', '') + '-06:00',
  expiration_date_to: moment().add(5, 'minute').toISOString().replace('Z', '') + '-06:00',
  external_reference: reservation.reservation_id
};
  
self.mercadopago.api.createPreference(preference, function (err, data){
  if (err) {
    return reject(err);
  } else {
    ...
  }
});

```

**Comment by elgambet** [comment]
Hay un [issue abierto](https://github.com/mercadopago/px-hybrid/issues/18)

**Comment by greggocabral** [comment]
Hola! 
Estoy teniendo el mismo problema en el checkout de mi deploy para Android.
Me funcionaba perfecto cuando usaba la prefId del tutorial, pero cuando creo mi propia preferencia me sale un cartel como [este](https://cloud.githubusercontent.com/assets/22642569/20025894/ca05ccdc-a2c9-11e6-9d76-e52398dca122.png) pero sin la opcion opción 'Reintentar'.
Ya lo intenté con mis credenciales de producción pero sigo teniendo el mismo problema.
Parece que la preferencia se genera bien porque la [URL de init point](https://www.mercadopago.com/mla/checkout/start?pref_id=44088366-17d916ce-e4a0-4fd5-84a9-9d796e23e4d2) funciona 
Alguna idea?
Gracias!

**Comment by DNAngeluS** [comment]
Hola @greggocabral la verdad que no tuvimos ningun tipo de respuesta de los devs de este proyecto asi que lo que terminamos haciendo es hacer una implementación 100% web ya que el plugin fallaba siempre. Lamentablemente no es una solución pero es lo que tuvimos que hacer.
