### ISSUE TITLE
[iOS] Error showCardWithInstallments Callback to Failure instead of Resolve

### ISSUE THREAD

**Issue by nlasso** [mercadopago/px-hybrid#23]
Utilizando el plugin con el nro de versión 1.1.9 el método ```showCardWithInstallments``` estaba funcionando bien. Luego de remover la versión anterior y actualizar al plugin 1.1.11 utilizando el comando ```cordova plugin add mercadopago-plugin```, con el mismo código (que funcionaba anteriormente), devuelve el siguiente objeto al callback de error:
```
{
    "payment_method": "{\"id\":\"visa\",\"name\":\"Visa\",\"payment_type_id\":\"credit_card\"}",
    "payer_cost": "{\"installmentAmount\":2,\"installments\":1,\"recommendedMessage\":\"1 cuota de $ 2,00 ($ 2,00)\",\"installmentRate\":0,\"totalAmount\":2,\"minAllowedAmount\":0,\"maxAllowedAmount\":0}",
    "token": "{\"usedDate\":\"\",\"id\":\"d1a57389a28fd25c472b78482f5b8294\",\"lastModifiedDate\":\"2017-03-19\",\"expirationMonth\":9,\"dueDate\":\"2017-03-27\",\"cardNumberLength\":0,\"lastFourDigits\":\"0121\",\"securityCodeLength\":3,\"firstSixDigit\":\"454075\",\"cardId\":null,\"luhnValidation\":\"1\",\"expirationYear\":2019,\"status\":\"active\",\"creationDate\":\"2017-03-19\"}",
    "issuer": "{\"id\":1,\"name\":\"Otro\"}"
}
```
Al actualizar al plugin que aparece como ```unstable``` bajandolo desde la URL que aparece como 1.1.10, funciona correctamente. 

XCode: 8.2.1
iOS: 10.2.1

Necesitaría saber si es un error conocido y si hay alguna forma de resolverlo para la versión 1.1.11. 

Desde ya muchas gracias!

**Comment by edentorres** [comment]
Hola! 

En la version 1.1.11 se cambio la llamada al metodo showCardWithInstallments a la siguiente:

MercadoPago.showCardWithInstallments(publicKey, site, amount, backgroundColor, enableBlackFont, **paymentRecovery**, paymentPreference, success, failure);

Este paymentRecovery es un objeto que puede enviarse a los componentes de cobro con tarjeta, y éste precargará los datos no sensibles del usuario, o si fuese un rechazo por falta de autorización sólo pedirá el código de seguridad. Solo esta disponible en android, en iOS envia siempre null.

Gracias por el aviso!

**Comment by nlasso** [comment]
Tienen alguna documentación del paymentRecovery para poder implementarlo? No lo encontré aquí http://mercadopago.github.io/px-hybrid/f2

**Comment by edentorres** [comment]
Así podes crear el objeto:
MercadoPago.createPaymentRecovery(payment, token, paymentMethod, payerCost, issuer, successCallback, errorCallback);

Y después se lo podes agregar a la llamada de showCardWithInstallments.
