### ISSUE TITLE
Error al agregar plugin luego de actualizar cocoapods

### ISSUE THREAD

**Issue by nlasso** [mercadopago/px-hybrid#25]
Luego de actualizar a CocoaPods (a pedido del plugin de MP) a la versión 1.2.0, tuve que regenerar la plataforma ios en cordova y al volver a agregar el plugin pasa lo siguiente:
```
cordova plugin add mercadopago-plugin
Fetching plugin "mercadopago-plugin" via npm
Installing "com.mercadopago.cordova.sdk" for android
Fetching plugin "cordova-plugin-add-swift-support" via npm
Installing "cordova-plugin-add-swift-support" for android
Installing "com.mercadopago.cordova.sdk" for ios
Installing "cordova-plugin-add-swift-support" for ios
Failed to install 'com.mercadopago.cordova.sdk':undefined
Error: Version should contain only numbers and dots
```

**Comment by edentorres** [comment]
Estuve averiguando y según [acá](https://github.com/phonegap/phonegap-plugin-push/issues/1465) es un problema que hay con CocoaPods 1.2.0 

Probe el plugin con CocoaPods 1.1.1 y no puedo reproducir el error. ¿Por qué el plugin te pidió que actualices a 1.2?

**Comment by nlasso** [comment]
Efectivamente! Gracias!
