### ISSUE TITLE
Imposible compilar en phonegap. You have not accepted the license agreements of the following SDK components

### ISSUE THREAD

**Issue by vousys** [mercadopago/px-hybrid#32]
Puede ser que tengan que actualizar el plugin para phonegap? xq estoy intentando compilar la app demo que uds subieron a git hace un tiempo https://github.com/mercadopago/px-hybrid/tree/example-phonegap  y solo si quito el plugin de uds, compilo bien

Este log me arroja.
Build Date: 2017-05-10 14:39:39 +0000
Subproject Path: CordovaLib
Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
File /.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [Android Support Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.91 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [Android Support Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by edentorres** [comment]
Hola!

Al parecer te esta faltando aceptar una licencia, no parece que sea problema del plugin. Te dejo aca estos links:

http://stackoverflow.com/questions/40392345/ionic-build-error-you-have-not-accepted-the-license-agreements-of-the-followin
http://stackoverflow.com/questions/40383323/cant-accept-license-agreement-android-sdk-platform-24/40383457#40383457

Espero que te sirvan!

**Comment by vousys** [comment]
Hola! no, porq si yo remuevo del config esta linea donde incluyo el plugin
de uds:
<plugin name="mercadopago-plugin" source="npm"/>
Genero el apk para produccion sin problemas. De hecho, vengo generando apks
todos los dias para diferentes proyectos q no incluyen MP

Podras probar de generar el proyecto ese demo que dejaron uds armado y vas
a ver que el build online de phonegap te tira eso. (Yo no compilo desde
consola, uso build.phonegap.com y los unicos archivos que tengo que poner
en mi proyecto son html,js y el config.xml)





[image: photo]

<http://facebook.com/vousys>  <http://us.linkedin.com/in/vosorio>
<http://twitter.com/vousys>  <http://instagram.com/vousys>
<http://behance.net/vousys>
Vero Osorio
Dev, VOUSYS
+54 011 4481 3751  <+54+911+4481+3751>*•* Skype: vousys
<#UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_UNIQUE_ID_SafeHtmlFilter_>
 *•*
 http://www.vousys.com  <http://www.vousys.com>*•* vosorio@vousys.com
<vosorio@vousys.com>*•*


2017-05-11 10:29 GMT-03:00 Edén Torres <notifications@github.com>:

**Comment by vousys** [comment]
@edentorres no lo cierres el issue, porfis proba de compilar el paquete del ejemplo de uds asi como esta en el cloud de phonegap (build.phonegap.com) y vas a ver q con el plugin de uds agregado, tira eso.
