### ISSUE TITLE
Error on IOS simulator not found the plugin MercadoPago or is not a CDVPlugin

### ISSUE THREAD

**Issue by brodriguezs** [mercadopago/px-hybrid#6]
This is the console log output for the IOS Simulator on an iPhone 6sPlus:

> Sep 13 16:55:07 MacBook-Pro-de-Geapps RUBE Padres[1854]: CDVPlugin class MercadoPagoPlugin (pluginName: MercadoPago) does not exist.
> Sep 13 16:55:07 MacBook-Pro-de-Geapps RUBE Padres[1854]: ERROR: Plugin 'MercadoPago' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
> Sep 13 16:55:07 MacBook-Pro-de-Geapps RUBE Padres[1854]: -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["MercadoPago504566576","MercadoPago","startCheckout",["TEST-ad365c37-8012-4014-84f5-6c895b3f8e0a","176234066-fc6d5d5e-2671-4073-ab49-362a98b720b5",null,false]]

This happen when click on the button with the function startCheckout(), and the build not shows errors. In android runs ok with the cards of test. This is only the test case implementation on the documentation page, and testing the functionally for IOS. Thanks in advance.

**Comment by edentorres** [comment]
Hello, I've just check the problem and it's working fine for me. 

I think it's and issue you are having with cordova not adding the plugin to your xcode project. 
This might help you: http://stackoverflow.com/questions/19447827/ios-unable-to-find-plugins-android-fine
Also can you open the xcode project, go to Build Phases and check that you have MercadoPagoSDK.framework in Embed Frameworks? If not, please add it. 

Hope it works.
