### ISSUE TITLE
Error de compilación: com.android.dex.DexException

### ISSUE THREAD

**Issue by sabrinapisol** [mercadopago/px-hybrid#7]
Estoy tratando de implementar MercadoPago SDK Hybrid en una app en ionic, y aparentemente hay algún conflicto con la versión de android sdk que usa otro plugin (sospecho que phonegap-plugin-push).
Luego de instalar el plugin, al intentar compilar para android obtengo el siguiente error:

Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzsg;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzsg;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

-----------------------------------------------------------
ionic plugins:
com.mercadopago.cordova.sdk 0.9.0 "MercadoPago"
cordova-plugin-add-swift-support 1.3.2 "AddSwiftSupport"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.8.1 "PushPlugin"

-----------------------------------------------------------
ionic info:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.3

-----------------------------------------------------------

¿Hay alguna manera de forzar la versión de sdk que usa este plugin para evitar el conflicto? Anteriormente he tenido el mismo problema con phonegap-facebook-plugin y pude solucionarlo cambiandole el framework en plugin.xml, pero en este caso no fue posible.

**Comment by edentorres** [comment]
Si, efectivamente esta generando conflicto con el otro plugin. Nosotros no agregamos la librería desde el plugin.xml entonces para solucionar el problema anda a:

Tu_proyecto/platforms/android/com.mercadopago.cordova.sdk/ y abrí el build.gradle que aparece.

Y remplaza todo el texto por esto:

` dependencies {
      compile ('com.mercadopago:sdk:2.0.1@aar') {
       transitive = true
       exclude group: 'com.google.android.gms'
   }
}`

Ahi eliminarías esta librería de nuestro proyecto.

Espero haberte ayudado!

**Comment by sabrinapisol** [comment]
Muchas gracias! finalmente implementamos la versión de JS, para el próximo proyecto intentaremos usar esta.
