### ISSUE TITLE
ReferenceError: MercadoPago is not defined

### ISSUE THREAD

**Issue by brunovinny** [mercadopago/px-hybrid#8]
Please, I need a final step-by-step to use MercadoPago's plugin with Ionic. I lost several weeks trying it but I got error's this message: "is not defined". I really need to solve this issue, but I don't got success. Below I'm posting the link to my issue's details:

http://stackoverflow.com/questions/39692783/adding-and-using-plugins-on-ionic/39693459#39693459

**Comment by matiasgualino** [comment]
Hi, did you read this docs: http://mercadopago.github.io/px-hybrid/ ??

This plugin make native calls when you use ˝MercadoPago". You should run in Android Emulator or Phone. 

For testing you can use: 
var publicKey = "TEST-ad365c37-8012-4014-84f5-6c895b3f8e0a";
 var prefId = "176234066-fc6d5d5e-2671-4073-ab49-362a98b720b5";

But if you wanna use your public key and preference_id:

- Credentials: https://www.mercadopago.com/mlb/account/credentials
- Make preferences: **In your backend (PHP for example)** https://www.mercadopago.com.ar/developers/en/tools/sdk/server/php/

Kind regards,

Matias.

**Comment by brunovinny** [comment]
Thank you very much Matias, It's running perfectly at android's simulator!

I'd read the documentation, but I've one last question. 

How do I customize the plugin's messages ? I'll be using this plugin with brazilians citizens, so the messages must be showed in portuguese.

**Comment by brunovinny** [comment]
Thank you very much Matias, It's running perfectly at android's simulator!

I'd read the documentation, but I've one last question.

How do I customize the plugin's messages ? I'll be using this plugin with brazilians citizens, so the messages must be showed in portuguese.

**Comment by matiasgualino** [comment]
I think your android's simulator language is English. 

Can you change language to portuguese and try again? At the moment just card form is in portuguese.
